# ------------------------------------------------------------------------
#
# Copyright (c) 2016, WSO2 Inc. (http://www.wso2.org) All Rights Reserved.
#
#   WSO2 Inc. licenses this file to you under the Apache License,
#   Version 2.0 (the "License"); you may not use this file except
#   in compliance with the License.
#   You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
#   Unless required by applicable law or agreed to in writing,
#   software distributed under the License is distributed on an
#   "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
#   KIND, either express or implied.  See the License for the
#   specific language governing permissions and limitations
#   under the License.
#
# ------------------------------------------------------------------------

FROM docker.wso2.com/wso2-cloud/tomcat:8.5.5-alpine3.4-oracle-jdk1.8.0

ENV APP_WAR ARTIFACT_NAME
ENV URL ARTIFACT_URL
ENV WEB_APP_HOME $TOMCAT_HOME_DIR/webapps/
ENV TOTAL_MEMORY VAL_TOTAL_MEMORY
ENV TAIL_LOG ENABLE_TAIL_LOG
ENV JFR_FLAG ENABLE_JFR

RUN wget "$URL" -O "$WEB_APP_HOME$APP_WAR"

CMD ["bash", "-c", "source /init.sh"]
